application: optimus-webwizard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: template/css
- url: /font
  static_dir: template/font
- url: /images
  static_dir: template/images
- url: /js
  static_dir: template/js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
